### ISSUE TITLE
这里改成安装 LTS 版本的命令会更好一点吗？:thinking:

### ISSUE THREAD

**Issue by wuhang2003** [ttimochan/mx-docs#2]
https://github.com/ttimochan/mx-docs/blob/453645038ee1f4954f7afa25953157cea0c6c2fe/src/deploy/index.md?plain=1#L54-L58

`nvm install --lts` 可以直接安装最新的 LTS 版本

**Comment by ttimochan** [comment]
> https://github.com/ttimochan/mx-docs/blob/453645038ee1f4954f7afa25953157cea0c6c2fe/src/deploy/index.md?plain=1#L54-L58
> 
> `nvm install --lts` 可以直接安装最新的 LTS 版本

但是 innei 不一定跟进 lts 版本，虽然这种可能性不大

**Comment by wuhang2003** [comment]
> > https://github.com/ttimochan/mx-docs/blob/453645038ee1f4954f7afa25953157cea0c6c2fe/src/deploy/index.md?plain=1#L54-L58
> > 
> > `nvm install --lts` 可以直接安装最新的 LTS 版本
> 
> 但是 innei 不一定跟进 lts 版本，虽然这种可能性不大

Current（Latest）不跟进就算了
LTS 怎么说都应该跟进的吧......

**Comment by ttimochan** [comment]
> > > https://github.com/ttimochan/mx-docs/blob/453645038ee1f4954f7afa25953157cea0c6c2fe/src/deploy/index.md?plain=1#L54-L58
> > > 
> > > `nvm install --lts` 可以直接安装最新的 LTS 版本
> > 
> > 但是 innei 不一定跟进 lts 版本，虽然这种可能性不大
> 
> Current（Latest）不跟进就算了
> LTS 怎么说都应该跟进的吧......

好，欢迎 commit

**Comment by wuhang2003** [comment]
> > > > https://github.com/ttimochan/mx-docs/blob/453645038ee1f4954f7afa25953157cea0c6c2fe/src/deploy/index.md?plain=1#L54-L58
> > > > 
> > > > `nvm install --lts` 可以直接安装最新的 LTS 版本
> > > 
> > > 
> > > 但是 innei 不一定跟进 lts 版本，虽然这种可能性不大
> > 
> > 
> > Current（Latest）不跟进就算了
> > LTS 怎么说都应该跟进的吧......
> 
> 好，欢迎 commit

https://github.com/ttimochan/mx-docs/commit/96fee3e3e17d7dbd65946bc21c01ec6703a498ce
