### ISSUE TITLE
请问大佬api后端如何进行配置

### ISSUE THREAD

**Issue by yuano0** [ttimochan/mx-docs#3]
## 问题
![A0AB402E-76B8-4ADE-8D92-4217AA84706B](https://user-images.githubusercontent.com/106160716/188397802-fd092ba2-a9a3-4fde-b5ed-06bdc6ed99f8.png)

我跟着up喵二君的视频配置到这里，弹幕提示和之前core的.env一样，我没太理解，请问大佬这个如何进行配置呀.
十分感谢◠‿◠

## 详细描述
api后端配置有问题

### 系统环境
ubuntu 22.04。linux内核版本是5.4.0

**Comment by ttimochan** [comment]
API 地址是你的后端域名+/api/v2 ，例如 我的后端域名是 api.example.com 那么 api 地址就是 https://api.example.com/api/v2   下面的网关地址 就是你的后端域名，例如 https://api.example.com

**Comment by ttimochan** [comment]
考虑加入说明

**Comment by yuano0** [comment]
配置好了谢谢大佬，记得勾选持久化。
